/**
 * Catálogo central de conquistas — única fonte de verdade para UI e desbloqueio.
 */
export const ACHIEVEMENT_CATALOG = [
  {
    id: 'first_exercise',
    name: 'Primeiro Passo',
    description: 'Complete seu primeiro exercício',
    icon: 'Star',
    color: 'text-blue-500',
    bgColor: 'bg-blue-50 dark:bg-blue-900/20',
    requirement: 'Completar 1 exercício',
    xp: 10,
    category: 'practice',
  },
  {
    id: 'streak_3',
    name: 'Iniciante Dedicado',
    description: 'Mantenha um streak de 3 dias',
    icon: 'Flame',
    color: 'text-orange-500',
    bgColor: 'bg-orange-50 dark:bg-orange-900/20',
    requirement: '3 dias de streak',
    xp: 50,
    category: 'streak',
  },
  {
    id: 'streak_7',
    name: 'Uma Semana Forte',
    description: 'Mantenha um streak de 7 dias',
    icon: 'Trophy',
    color: 'text-yellow-500',
    bgColor: 'bg-yellow-50 dark:bg-yellow-900/20',
    requirement: '7 dias de streak',
    xp: 100,
    category: 'streak',
  },
  {
    id: 'streak_14',
    name: 'Duas Semanas!',
    description: 'Mantenha um streak de 14 dias',
    icon: 'Award',
    color: 'text-purple-500',
    bgColor: 'bg-purple-50 dark:bg-purple-900/20',
    requirement: '14 dias de streak',
    xp: 200,
    category: 'streak',
  },
  {
    id: 'streak_30',
    name: 'Mês Completo',
    description: 'Mantenha um streak de 30 dias',
    icon: 'Trophy',
    color: 'text-pink-500',
    bgColor: 'bg-pink-50 dark:bg-pink-900/20',
    requirement: '30 dias de streak',
    xp: 500,
    category: 'streak',
  },
  {
    id: 'streak_60',
    name: 'Dois Meses!',
    description: 'Mantenha um streak de 60 dias',
    icon: 'Award',
    color: 'text-indigo-500',
    bgColor: 'bg-indigo-50 dark:bg-indigo-900/20',
    requirement: '60 dias de streak',
    xp: 1000,
    category: 'streak',
  },
  {
    id: 'streak_100',
    name: 'Lenda do Streak!',
    description: 'Mantenha um streak de 100 dias',
    icon: 'Star',
    color: 'text-amber-500',
    bgColor: 'bg-amber-50 dark:bg-amber-900/20',
    requirement: '100 dias de streak',
    xp: 2000,
    category: 'streak',
  },
  {
    id: 'exercises_50',
    name: 'Praticante',
    description: 'Complete 50 exercícios',
    icon: 'Target',
    color: 'text-green-500',
    bgColor: 'bg-green-50 dark:bg-green-900/20',
    requirement: '50 exercícios',
    xp: 100,
    category: 'practice',
  },
  {
    id: 'exercises_100',
    name: 'Veterano',
    description: 'Complete 100 exercícios',
    icon: 'Zap',
    color: 'text-cyan-500',
    bgColor: 'bg-cyan-50 dark:bg-cyan-900/20',
    requirement: '100 exercícios',
    xp: 300,
    category: 'practice',
  },
  {
    id: 'perfect_accuracy',
    name: 'Perfeição',
    description: 'Atinja 100% de precisão em 10 exercícios seguidos',
    icon: 'Star',
    color: 'text-yellow-600',
    bgColor: 'bg-yellow-50 dark:bg-yellow-900/20',
    requirement: '10 acertos consecutivos',
    xp: 250,
    category: 'practice',
  },
  {
    id: 'master_learner',
    name: 'Mestre do Conhecimento',
    description: 'Complete todas as lições de um subtópico',
    icon: 'Brain',
    color: 'text-indigo-500',
    bgColor: 'bg-indigo-50 dark:bg-indigo-900/20',
    requirement: 'Completar 1 subtópico',
    xp: 400,
    category: 'learn',
  },
  {
    id: 'level_5',
    name: 'Em Ascensão',
    description: 'Alcance o nível 5',
    icon: 'TrendingUp',
    color: 'text-primary-500',
    bgColor: 'bg-primary-50 dark:bg-primary-900/20',
    requirement: 'Nível 5',
    xp: 75,
    category: 'level',
  },
  {
    id: 'level_10',
    name: 'Estudante Avançado',
    description: 'Alcance o nível 10',
    icon: 'Trophy',
    color: 'text-purple-600',
    bgColor: 'bg-purple-50 dark:bg-purple-900/20',
    requirement: 'Nível 10',
    xp: 150,
    category: 'level',
  },
  {
    id: 'daily_goal',
    name: 'Meta do Dia',
    description: 'Complete sua meta diária de exercícios',
    icon: 'Target',
    color: 'text-green-600',
    bgColor: 'bg-green-50 dark:bg-green-900/20',
    requirement: 'Meta diária completa',
    xp: 25,
    category: 'daily',
  },
];

export const ACHIEVEMENT_BY_ID = Object.fromEntries(
  ACHIEVEMENT_CATALOG.map((a) => [a.id, a])
);

/** Desafios diários exibidos no Dashboard */
export const WEEKLY_CHALLENGES = [
  {
    id: 'week_practice_15',
    title: 'Maratonista',
    description: 'Complete 15 exercícios esta semana',
    target: 15,
    metric: 'attempts',
    xpBonus: 80,
    icon: 'Zap',
  },
  {
    id: 'week_lessons_5',
    title: 'Estudioso',
    description: 'Conclua 5 lições esta semana',
    target: 5,
    metric: 'lessons',
    xpBonus: 100,
    icon: 'BookOpen',
  },
  {
    id: 'week_xp_300',
    title: 'Acumulador',
    description: 'Ganhe 300 XP esta semana',
    target: 300,
    metric: 'weeklyXP',
    xpBonus: 120,
    icon: 'Trophy',
  },
];

export const DAILY_CHALLENGES = [
  {
    id: 'practice_3',
    title: 'Praticante do dia',
    description: 'Complete 3 exercícios hoje',
    target: 3,
    metric: 'attempts',
    xpBonus: 15,
    icon: 'Target',
  },
  {
    id: 'correct_2',
    title: 'Precisão em dia',
    description: 'Acerte 2 exercícios hoje',
    target: 2,
    metric: 'correct',
    xpBonus: 20,
    icon: 'CheckCircle',
  },
  {
    id: 'lesson_1',
    title: 'Explorador',
    description: 'Conclua 1 lição hoje',
    target: 1,
    metric: 'lessons',
    xpBonus: 25,
    icon: 'BookOpen',
  },
];
